env:
  node: true
parserOptions:
  sourceType: script
extends: 'airbnb-base'
rules:
  strict:
    - error
    - global
  max-len: off
  # newline-after-var: off
  no-multiple-empty-lines:
    - error
    - max: 1
  comma-dangle:
    - error
    - never
  newline-per-chained-call:
    - error
    - ignoreChainWithDepth: 6
  no-nested-ternary: off
  no-use-before-define:
    - error
    - functions: false
  no-param-reassign:
    - error
    - props: false
  no-return-assign:
    - error
    - except-parens
  object-curly-newline:
    - error
    - consistent: true
  indent:
    - error
    - 2
    - SwitchCase: 1
  global-require: off
  arrow-parens:
    - error
    - as-needed
  no-plusplus: off
  no-bitwise: off
  no-await-in-loop: off
  